exec-once=noctalia
animations=1
layer_animations = 1
bordercolor = 0x595959aa



# Bind

bind = SUPER,r,reload_config
bind = SUPER,space,spawn,fuzzel
bind = SUPER,Enter,spawn,kitty
bind = SUPER,q,killclient
bind = SUPER,f,togglefloating
bind = SUPER,F,toggle_all_floating
bind = SUPER,k,focusdir,up
bind = SUPER,j,focusdir,down
bind = SUPER,h,focusdir,left
bind = SUPER,l,focusdir,right
bind = SUPER,K,focus_window_or_workspace,up
bind = SUPER,J,focus_window_or_workspace,down
bind = SUPER,H,focus_window_or_workspace,left
bind = SUPER,L,focus_window_or_workspace,right

# Bind Layout

bind=SUPER,t,setlayout,tile
bind=SUPER,f,togglefloating
bind=SUPER,m,setlayout,monocle
bind=SUPER,v,setlayout,vertical_grid
bind=SUPER+SHIFT,v,setlayout,vertical_scroller
bind = SUPER,n,switch_layout


